// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using SixLabors.ImageSharp.PixelFormats;

namespace SixLabors.ImageSharp.Drawing.Processing.Backends;

/// <summary>
/// Defines the representation shared by shader-effect passes and their retained write-back fills.
/// </summary>
internal static class WebGPUShaderEffectWorkingTexture
{
    /// <summary>
    /// Gets the associated, unit-encoded floating-point representation used between shader-effect passes.
    /// </summary>
    /// <remarks>
    /// Shader arithmetic remains 32-bit floating point. Storing a pass result in this texture rounds
    /// each component to IEEE 754 binary16 until the next pass loads it back into 32-bit registers.
    /// <c>Rgba16Float</c> is used because it retains substantially more precision than normalized
    /// 8-bit layer storage while consuming 8 bytes per pixel. <c>Rgba32Float</c> would consume
    /// 16 bytes per pixel and would therefore double both the memory occupied by the two ping-pong
    /// textures and the texture traffic generated by every effect pass. The binary16 store can still
    /// select an adjacent final 8-bit value where the unrounded 32-bit result lies near a quantization
    /// boundary, so shader effects are not guaranteed to be bit-identical to CPU operations that retain
    /// 32-bit values until their final destination conversion.
    /// </remarks>
    public static WebGPUTargetDescriptor Descriptor { get; } = new(
        WebGPUTextureFormat.Rgba16Float,
        PixelAlphaRepresentation.Associated,
        WebGPUTargetNumericEncoding.Unit);
}
