// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using System.Numerics;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.Drawing.Processing.Backends;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using WebGPUExternalSurfaceDemo.Controls;
using Brush = SixLabors.ImageSharp.Drawing.Processing.Brush;
using Brushes = SixLabors.ImageSharp.Drawing.Processing.Brushes;
using Color = SixLabors.ImageSharp.Color;
using GraphicsOptions = SixLabors.ImageSharp.GraphicsOptions;
using Size = SixLabors.ImageSharp.Size;

namespace WebGPUExternalSurfaceDemo.Scenes;

/// <summary>
/// Displays an interactive, animated nebula generated by a custom WGSL layer effect.
/// Moving the pointer stirs the gas, clicking launches a shockwave, and the wheel changes scale.
/// The same effect can execute through its equivalent CPU fallback when WebGPU is unavailable.
/// </summary>
internal sealed class ShaderEffectsScene : RenderScene
{
    private static readonly GraphicsOptions LayerOptions = new();
    private static readonly Brush OpaqueLayerBrush = Brushes.Solid(Color.Black);

    // The effect is an immutable uniform snapshot. Animation replaces this small object,
    // while WebGPUShaderProgram continues to reuse the source/layout compiled below.
    private LivingNebulaShaderEffect shaderEffect = new(
        new LivingNebulaShaderOptions
        {
            Size = new Size(1280, 800),
            SwirlCenter = new Vector2(640F, 400F),
            Zoom = 1F,
            PulseOrigin = new Vector2(640F, 400F),
            PulseAge = 10F,
        });

    // Input is retained in device pixels because the shader receives effect-local pixel
    // coordinates and performs its own aspect-correct normalization from the viewport size.
    private Vector2 pointer;
    private Vector2 smoothedSwirl;
    private Vector2 pulseOrigin;
    private float elapsedSeconds;
    private float pulseStart = -10F;
    private float zoom = 1F;
    private bool hasPointer;
    private bool pointerDown;

    /// <inheritdoc />
    public override string DisplayName => "Custom WGSL · Living Nebula";

    /// <inheritdoc />
    protected override WebGPURenderMode RenderMode => WebGPURenderMode.Continuous;

    /// <inheritdoc />
    protected override Control CreateContent(WebGPURenderControl renderControl)
    {
        // The explanation belongs to the scene because it describes the generated image
        // and gestures. WinForms owns its lifetime after it joins the control tree.
        Label descriptionLabel = new()
        {
            AutoSize = true,
            BackColor = System.Drawing.Color.FromArgb(160, 0, 0, 0),
            ForeColor = System.Drawing.Color.White,
            Font = new Font(FontFamily.GenericSansSerif, 10F),
            Padding = new Padding(10),
            Location = new Point(10, 10),
            Text =
                "LIVING NEBULA — CUSTOM WGSL\n" +
                "Domain-warped clouds, fire cores, and two twinkling star fields\n" +
                "Move to stir  ·  Hold to intensify  ·  Click for shockwave  ·  Wheel to zoom",
        };

        renderControl.Controls.Add(descriptionLabel);
        return renderControl;
    }

    /// <inheritdoc />
    public override void OnHostLoaded(WebGPUDeviceContext deviceContext) =>

        // Compile the immutable WGSL program while the first tab is visible. Uniform values
        // change every frame, but every snapshot shares this cached program and pipeline.
        deviceContext.Precompile(this.shaderEffect);

    /// <inheritdoc />
    public override void Paint(DrawingCanvas canvas, TimeSpan deltaTime)
    {
        float deltaSeconds = Math.Clamp((float)deltaTime.TotalSeconds, 0F, 0.1F);
        this.elapsedSeconds = (this.elapsedSeconds + deltaSeconds) % 1000F;

        Size viewport = canvas.Bounds.Size;
        Vector2 viewportCenter = new(viewport.Width * 0.5F, viewport.Height * 0.5F);
        Vector2 targetSwirl = this.hasPointer ? this.pointer : viewportCenter;
        if (this.smoothedSwirl == Vector2.Zero)
        {
            this.smoothedSwirl = targetSwirl;
            this.pulseOrigin = viewportCenter;
        }

        // Exponential smoothing is frame-rate independent: the cursor feels equally
        // fluid on a 60 Hz display and on a faster or temporarily delayed frame loop.
        float follow = 1F - MathF.Exp(-7F * deltaSeconds);
        this.smoothedSwirl = Vector2.Lerp(this.smoothedSwirl, targetSwirl, follow);

        float pulseAge = this.elapsedSeconds - this.pulseStart;
        if (pulseAge < 0F)
        {
            // elapsedSeconds wraps to keep long-running shader coordinates precise. A pulse
            // crossing that wrap is still measured against the same thousand-second period.
            pulseAge += 1000F;
        }

        // Effects are immutable snapshots. Rebuilding the small uniform payload does not
        // recompile WGSL: the source and layout resolve to the same cached shader program.
        this.shaderEffect = new LivingNebulaShaderEffect(
            new LivingNebulaShaderOptions
            {
                Size = viewport,
                Time = this.elapsedSeconds,
                SwirlCenter = this.smoothedSwirl,
                PointerDown = this.pointerDown,
                Zoom = this.zoom,
                PulseOrigin = this.pulseOrigin,
                PulseAge = pulseAge,
            });

        // Filling the complete layer gives the procedural shader a pixel at every output
        // position. The effect intentionally generates an opaque scene and ignores input color.
        canvas.SaveLayer(LayerOptions, canvas.Bounds, this.shaderEffect);
        canvas.Fill(OpaqueLayerBrush, canvas.Bounds);
        canvas.Restore();
    }

    /// <inheritdoc />
    public override void OnMouseDown(MouseEventArgs e)
    {
        this.pointer = new Vector2(e.X, e.Y);
        this.hasPointer = true;
        this.pointerDown = true;

        if (e.Button == MouseButtons.Left)
        {
            this.pulseOrigin = this.pointer;
            this.pulseStart = this.elapsedSeconds;
        }
    }

    /// <inheritdoc />
    public override void OnMouseMove(MouseEventArgs e)
    {
        this.pointer = new Vector2(e.X, e.Y);
        this.hasPointer = true;
        this.pointerDown = (e.Button & MouseButtons.Left) != 0;
    }

    /// <inheritdoc />
    public override void OnMouseUp(MouseEventArgs e) => this.pointerDown = false;

    /// <inheritdoc />
    public override void OnMouseWheel(MouseEventArgs e)
    {
        this.pointer = new Vector2(e.X, e.Y);
        this.hasPointer = true;

        // The shader multiplies its centered coordinates by zoom. Smaller values
        // therefore reveal a closer view while larger values reveal more space.
        float factor = e.Delta > 0 ? 0.88F : 1F / 0.88F;
        this.zoom = Math.Clamp(this.zoom * factor, 0.42F, 3F);
    }

    /// <summary>
    /// Contains one immutable set of values shared by a shader pass and its CPU fallback.
    /// </summary>
    private readonly struct LivingNebulaShaderOptions
    {
        /// <summary>Gets the effect-local output size in pixels.</summary>
        public Size Size { get; init; }

        /// <summary>Gets the animation time in seconds.</summary>
        public float Time { get; init; }

        /// <summary>Gets the smoothed vortex center in effect-local pixels.</summary>
        public Vector2 SwirlCenter { get; init; }

        /// <summary>Gets a value indicating whether a pressed pointer button should intensify the vortex.</summary>
        public bool PointerDown { get; init; }

        /// <summary>Gets the scale applied to the procedural coordinate system.</summary>
        public float Zoom { get; init; }

        /// <summary>Gets the most recent shockwave origin in effect-local pixels.</summary>
        public Vector2 PulseOrigin { get; init; }

        /// <summary>Gets the elapsed time since the most recent shockwave started.</summary>
        public float PulseAge { get; init; }
    }

    /// <summary>
    /// Generates the living-nebula image from domain-warped noise and sparse procedural stars.
    /// </summary>
    private sealed class LivingNebulaShaderEffect : WebGPUShaderLayerEffect
    {
        private const string ShaderSource = """
            fn hash21(value: vec2<f32>) -> f32 {
                // Wrapping lattice coordinates prevents the sine hash losing useful low bits
                // when animated coordinates grow. Its 256-cell period is larger than the
                // procedural domain visible in this scene.
                let wrapped = value - (floor(value / 256.0) * 256.0);
                return fract(sin(dot(wrapped, vec2<f32>(127.1, 311.7))) * 43758.5453);
            }

            fn value_noise(position: vec2<f32>) -> f32 {
                let cell = floor(position);
                let local = fract(position);
                let blend = local * local * (vec2<f32>(3.0) - (2.0 * local));
                let lower_left = hash21(cell);
                let lower_right = hash21(cell + vec2<f32>(1.0, 0.0));
                let upper_left = hash21(cell + vec2<f32>(0.0, 1.0));
                let upper_right = hash21(cell + vec2<f32>(1.0, 1.0));
                return mix(
                    mix(lower_left, lower_right, blend.x),
                    mix(upper_left, upper_right, blend.x),
                    blend.y);
            }

            fn rotate(position: vec2<f32>, angle: f32) -> vec2<f32> {
                let cosine = cos(angle);
                let sine = sin(angle);
                return vec2<f32>(
                    (cosine * position.x) - (sine * position.y),
                    (sine * position.x) + (cosine * position.y));
            }

            fn fbm(initial_position: vec2<f32>) -> f32 {
                var position = initial_position;
                var value = 0.0;
                var amplitude = 0.5;

                // Six octaves retain fine cloud structure without turning the sample into
                // a shader stress test. Rotation prevents obvious axis-aligned repetition.
                for (var octave: i32 = 0; octave < 6; octave = octave + 1) {
                    value = value + (amplitude * value_noise(position));
                    position = (rotate(position, 0.6435011) * 2.0) + vec2<f32>(1.7);
                    amplitude = amplitude * 0.5;
                }

                return value;
            }

            fn star_layer(position: vec2<f32>, scale: f32, time: f32, layer: f32) -> f32 {
                let star_position = position / scale;
                let cell = floor(star_position);
                let random = hash21(cell + vec2<f32>(layer * 13.0, layer * 7.0));
                let threshold = 0.93 + (layer * 0.02);
                if (random <= threshold) {
                    return 0.0;
                }

                // Each occupied cell gets a stable sub-cell offset. Only brightness changes,
                // so stars twinkle without swimming across the image during animation.
                let jitter = vec2<f32>(
                    hash21(cell + vec2<f32>(1.7 + layer, 3.1)),
                    hash21(cell + vec2<f32>(4.2, 8.3 + layer))) - vec2<f32>(0.5);
                let distance_to_star = length(fract(star_position) - vec2<f32>(0.5) - (jitter * 0.6));
                let twinkle = 0.55 + (0.45 * sin((time * (2.0 + (random * 7.0))) + (random * 40.0)));
                let point = 1.0 - smoothstep(0.0, 0.42, distance_to_star);
                return point * twinkle * (0.7 + (0.6 * random));
            }

            fn layer_effect(position: vec2<f32>) -> vec4<f32> {
                let resolution = imagesharp_uniforms.resolution;
                let zoom = imagesharp_uniforms.zoom;
                let time = imagesharp_uniforms.time;
                var uv = ((position - (resolution * 0.5)) / resolution.y) * zoom;
                let swirl_center = ((imagesharp_uniforms.swirl_center - (resolution * 0.5)) / resolution.y) * zoom;
                let from_swirl = uv - swirl_center;
                let swirl_distance = length(from_swirl);

                // Space is rotated around the pointer before noise is evaluated. Holding the
                // button increases the deformation while its exponential falloff keeps distant
                // gas stable and makes the gesture read as a local vortex.
                let swirl_strength = (0.55 + (imagesharp_uniforms.pointer_down * 0.9)) * exp(-swirl_distance * 2.8);
                let swirl_angle = swirl_strength / ((swirl_distance * 2.4) + 0.16);
                uv = swirl_center + rotate(from_swirl, swirl_angle);

                let drift_time = time * 0.06;
                let noise_position = (uv + vec2<f32>(drift_time * 0.35, drift_time * 0.12)) * 1.6;

                // Domain warping feeds two noise fields into a third. The resulting coordinate
                // distortion creates curling filaments rather than ordinary cloudy value noise.
                let first_warp = vec2<f32>(
                    fbm(noise_position + vec2<f32>(0.0, drift_time)),
                    fbm(noise_position + vec2<f32>(5.2, 1.3) - vec2<f32>(drift_time)));
                let second_warp = vec2<f32>(
                    fbm(noise_position + (3.0 * first_warp) + vec2<f32>(1.7, 9.2) + vec2<f32>(drift_time * 0.5)),
                    fbm(noise_position + (3.0 * first_warp) + vec2<f32>(8.3, 2.8) - vec2<f32>(drift_time * 0.4)));
                let warped_noise = fbm(noise_position + (2.4 * second_warp));

                var density = warped_noise * (0.6 + (0.7 * length(second_warp)));
                density = clamp((density - 0.34) * 2.0, 0.0, 1.0);
                density = pow(density, 2.1);

                // A click emits a two-second ring in the same aspect-correct coordinate system.
                // It brightens only a narrow band instead of filling the area behind the wave.
                var wave = 0.0;
                if (imagesharp_uniforms.pulse_age >= 0.0 && imagesharp_uniforms.pulse_age < 2.0) {
                    let pulse_position = ((imagesharp_uniforms.pulse_origin - (resolution * 0.5)) / resolution.y) * zoom;
                    let pulse_distance = length(uv - pulse_position);
                    let wave_radius = imagesharp_uniforms.pulse_age * 1.1;
                    let ring = exp(-pow((pulse_distance - wave_radius) * 12.0, 2.0));
                    wave = ring * (1.0 - (imagesharp_uniforms.pulse_age * 0.5));
                    density = density + (wave * 0.35);
                }

                let void_color = vec3<f32>(0.006, 0.010, 0.035);
                let indigo = vec3<f32>(0.05, 0.07, 0.24);
                let violet = vec3<f32>(0.26, 0.09, 0.46);
                let magenta = vec3<f32>(0.72, 0.16, 0.50);
                let ember = vec3<f32>(0.95, 0.45, 0.28);
                var color = mix(void_color, indigo, smoothstep(0.02, 0.22, density));
                color = mix(color, violet, smoothstep(0.20, 0.50, density));
                color = mix(color, magenta, smoothstep(0.52, 0.82, density));
                color = mix(color, ember, smoothstep(0.88, 1.0, density) * (0.25 + (0.45 * second_warp.x)));

                // A cool boundary color separates adjacent warped fields, while the orange
                // grade remains confined to the densest knots and reads as fire inside gas.
                let boundary = 1.0 - smoothstep(0.0, 0.12, abs(first_warp.x - first_warp.y));
                color = color + (vec3<f32>(0.04, 0.16, 0.24) * boundary * 0.35);
                color = color + (vec3<f32>(0.40, 0.70, 1.0) * wave * 0.9);

                var stars = star_layer(position, 7.0, time, 0.0);
                stars = stars + star_layer(position + vec2<f32>(19.0, 31.0), 13.0, time, 1.0);
                stars = stars * (1.0 - (smoothstep(0.35, 0.85, density) * 0.85));
                color = color + (vec3<f32>(0.85, 0.92, 1.0) * stars);

                let core = exp(-length(uv) * 2.6);
                color = color + (vec3<f32>(0.28, 0.10, 0.40) * core * 0.35);

                let viewport_position = (position / resolution) - vec2<f32>(0.5);
                let vignette = 1.0 - smoothstep(0.30, 1.20, length(viewport_position));
                color = color * vignette * 0.85;

                // This filmic curve rolls intense cloud cores toward white while preserving
                // saturated mid-tones. Clamp only after tone mapping to keep highlights smooth.
                color = (color * ((2.51 * color) + vec3<f32>(0.03))) /
                    ((color * ((2.43 * color) + vec3<f32>(0.59))) + vec3<f32>(0.14));
                return vec4<f32>(clamp(color, vec3<f32>(0.0), vec3<f32>(1.0)), 1.0);
            }
            """;

        // These names form the complete contract between the immutable C# options snapshot
        // and imagesharp_uniforms in WGSL. The same values also feed the CPU implementation.
        private static readonly WebGPUShaderUniformLayout UniformLayout = new(
        [
            new WebGPUShaderUniform("time", WebGPUShaderUniformType.Float32, 1),
            new WebGPUShaderUniform("resolution", WebGPUShaderUniformType.Vector2, 1),
            new WebGPUShaderUniform("swirl_center", WebGPUShaderUniformType.Vector2, 1),
            new WebGPUShaderUniform("pointer_down", WebGPUShaderUniformType.Float32, 1),
            new WebGPUShaderUniform("zoom", WebGPUShaderUniformType.Float32, 1),
            new WebGPUShaderUniform("pulse_origin", WebGPUShaderUniformType.Vector2, 1),
            new WebGPUShaderUniform("pulse_age", WebGPUShaderUniformType.Float32, 1),
        ]);

        /// <summary>
        /// Initializes a shader effect from one immutable animation and interaction snapshot.
        /// </summary>
        /// <param name="options">The values shared by the WGSL pass and CPU fallback.</param>
        public LivingNebulaShaderEffect(LivingNebulaShaderOptions options)
            : base(ShaderSource, UniformLayout, CreateFallback(options)) =>

            // The base type creates and freezes the pass. The effect supplies only values
            // matching its declared layout, which is the complete custom-shader workflow.
            this.AddShaderPass(uniforms =>
            {
                uniforms.SetFloat32("time", options.Time);
                uniforms.SetVector2("resolution", new Vector2(options.Size.Width, options.Size.Height));
                uniforms.SetVector2("swirl_center", options.SwirlCenter);
                uniforms.SetFloat32("pointer_down", options.PointerDown ? 1F : 0F);
                uniforms.SetFloat32("zoom", options.Zoom);
                uniforms.SetVector2("pulse_origin", options.PulseOrigin);
                uniforms.SetFloat32("pulse_age", options.PulseAge);
            });

        /// <summary>
        /// Creates the CPU image operation that reproduces the procedural WGSL pass.
        /// </summary>
        /// <param name="options">The immutable animation and interaction values for the frame.</param>
        /// <returns>The equivalent CPU image operation.</returns>
        private static Action<IImageProcessingContext> CreateFallback(LivingNebulaShaderOptions options)
            => context => context.ProcessPixelRowsAsVector4(
                (span, origin) =>
                {
                    Vector2 resolution = new(options.Size.Width, options.Size.Height);
                    for (int x = 0; x < span.Length; x++)
                    {
                        // Pixel-row processing supplies integer row origins. The half-pixel offset
                        // matches layer_effect's pixel-center coordinate contract on WebGPU.
                        Vector2 position = new(origin.X + x + 0.5F, origin.Y + 0.5F);
                        span[x] = new Vector4(RenderPixel(position, resolution, options), 1F);
                    }
                },
                PixelConversionModifiers.Scale | PixelConversionModifiers.UnPremultiply);

        /// <summary>
        /// Evaluates the nebula color for one effect-local pixel.
        /// </summary>
        /// <param name="position">The effect-local pixel-center position.</param>
        /// <param name="resolution">The effect-local output size.</param>
        /// <param name="options">The immutable animation and interaction values for the frame.</param>
        /// <returns>The unassociated opaque RGB color.</returns>
        private static Vector3 RenderPixel(Vector2 position, Vector2 resolution, LivingNebulaShaderOptions options)
        {
            // Normalize against viewport height so circles and radial falloffs remain round
            // on non-square surfaces. Zoom scales this effect-local coordinate system only.
            Vector2 uv = ((position - (resolution * 0.5F)) / resolution.Y) * options.Zoom;
            Vector2 swirlPosition = ((options.SwirlCenter - (resolution * 0.5F)) / resolution.Y) * options.Zoom;
            Vector2 fromSwirl = uv - swirlPosition;
            float swirlDistance = fromSwirl.Length();

            // Rotate sample space around the smoothed pointer. The exponential falloff
            // confines deformation to nearby gas; holding the pointer strengthens it.
            float swirlStrength = (0.55F + (options.PointerDown ? 0.9F : 0F)) * MathF.Exp(-swirlDistance * 2.8F);
            float swirlAngle = swirlStrength / ((swirlDistance * 2.4F) + 0.16F);
            uv = swirlPosition + Rotate(fromSwirl, swirlAngle);

            // Slow translation makes the nebula breathe without causing visible texture
            // swimming. The coordinates stay small enough for the sine hash below.
            float driftTime = options.Time * 0.06F;
            Vector2 noisePosition = (uv + new Vector2(driftTime * 0.35F, driftTime * 0.12F)) * 1.6F;

            // Domain warping evaluates two vector-valued noise stages and feeds them into
            // the final fBm lookup. This bends ordinary noise into long curling filaments.
            Vector2 firstWarp = new(
                Fbm(noisePosition + new Vector2(0F, driftTime)),
                Fbm(noisePosition + new Vector2(5.2F, 1.3F) - new Vector2(driftTime)));

            Vector2 secondWarp = new(
                Fbm(noisePosition + (3F * firstWarp) + new Vector2(1.7F, 9.2F) + new Vector2(driftTime * 0.5F)),
                Fbm(noisePosition + (3F * firstWarp) + new Vector2(8.3F, 2.8F) - new Vector2(driftTime * 0.4F)));

            // Remove the low fBm floor, expand the useful range, and apply a soft gamma.
            // Empty regions remain near-black while only folded ridges become luminous.
            float density = Fbm(noisePosition + (2.4F * secondWarp)) * (0.6F + (0.7F * secondWarp.Length()));
            density = Math.Clamp((density - 0.34F) * 2F, 0F, 1F);
            density = MathF.Pow(density, 2.1F);

            float wave = 0F;
            if (options.PulseAge is >= 0F and < 2F)
            {
                // Evaluate the click in the same aspect-correct space as the clouds. Squaring
                // the signed distance to the expanding radius produces a narrow Gaussian ring.
                Vector2 pulsePosition = ((options.PulseOrigin - (resolution * 0.5F)) / resolution.Y) * options.Zoom;
                float pulseDistance = Vector2.Distance(uv, pulsePosition);
                float waveRadius = options.PulseAge * 1.1F;
                float ringDistance = (pulseDistance - waveRadius) * 12F;
                wave = MathF.Exp(-(ringDistance * ringDistance)) * (1F - (options.PulseAge * 0.5F));
                density += wave * 0.35F;
            }

            // Layer color bands over the shaped density instead of mapping noise directly
            // to RGB. This keeps the void cool, the cloud body saturated, and only the
            // densest folded knots hot enough to reach the orange fire color.
            Vector3 color = Vector3.Lerp(new Vector3(0.006F, 0.010F, 0.035F), new Vector3(0.05F, 0.07F, 0.24F), SmoothStep(0.02F, 0.22F, density));
            color = Vector3.Lerp(color, new Vector3(0.26F, 0.09F, 0.46F), SmoothStep(0.20F, 0.50F, density));
            color = Vector3.Lerp(color, new Vector3(0.72F, 0.16F, 0.50F), SmoothStep(0.52F, 0.82F, density));
            color = Vector3.Lerp(
                color,
                new Vector3(0.95F, 0.45F, 0.28F),
                SmoothStep(0.88F, 1F, density) * (0.25F + (0.45F * secondWarp.X)));

            // A teal seam where the first warp channels meet adds depth between nearby
            // folds. The shockwave is then graded cyan-white independently of density.
            float boundary = 1F - SmoothStep(0F, 0.12F, MathF.Abs(firstWarp.X - firstWarp.Y));
            color += new Vector3(0.04F, 0.16F, 0.24F) * boundary * 0.35F;
            color += new Vector3(0.40F, 0.70F, 1F) * wave * 0.9F;

            // Two cell sizes create near and far star fields. Dense gas occludes most of
            // their light so stars appear behind the nebula rather than painted over it.
            float stars = StarLayer(position, 7F, options.Time, 0F) + StarLayer(position + new Vector2(19F, 31F), 13F, options.Time, 1F);
            stars *= 1F - (SmoothStep(0.35F, 0.85F, density) * 0.85F);
            color += new Vector3(0.85F, 0.92F, 1F) * stars;

            float core = MathF.Exp(-uv.Length() * 2.6F);
            color += new Vector3(0.28F, 0.10F, 0.40F) * core * 0.35F;

            // The vignette anchors the composition without clipping the corners abruptly.
            Vector2 viewportPosition = (position / resolution) - new Vector2(0.5F);
            float vignette = 1F - SmoothStep(0.30F, 1.20F, viewportPosition.Length());
            color *= vignette * 0.85F;

            // Apply the same rational filmic curve as WGSL. Values remain unconstrained
            // until this final stage so bright filaments roll smoothly toward white.
            Vector3 numerator = color * ((2.51F * color) + new Vector3(0.03F));
            Vector3 denominator = (color * ((2.43F * color) + new Vector3(0.59F))) + new Vector3(0.14F);
            return Vector3.Clamp(numerator / denominator, Vector3.Zero, Vector3.One);
        }

        /// <summary>
        /// Evaluates six octaves of fractal Brownian motion at a procedural coordinate.
        /// </summary>
        /// <param name="position">The procedural noise coordinate.</param>
        /// <returns>The accumulated noise value.</returns>
        private static float Fbm(Vector2 position)
        {
            float value = 0F;
            float amplitude = 0.5F;

            // Each octave doubles frequency and halves amplitude. Rotating between
            // octaves prevents repeated horizontal and vertical bands in the cloud.
            for (int octave = 0; octave < 6; octave++)
            {
                value += amplitude * ValueNoise(position);
                position = (Rotate(position, 0.6435011F) * 2F) + new Vector2(1.7F);
                amplitude *= 0.5F;
            }

            return value;
        }

        /// <summary>
        /// Evaluates smoothly interpolated two-dimensional value noise.
        /// </summary>
        /// <param name="position">The procedural noise coordinate.</param>
        /// <returns>The interpolated lattice value.</returns>
        private static float ValueNoise(Vector2 position)
        {
            // Interpolate deterministic values assigned to the four lattice corners.
            // Cubic Hermite weights remove derivative discontinuities at cell edges.
            Vector2 cell = new(MathF.Floor(position.X), MathF.Floor(position.Y));
            Vector2 local = new(Fract(position.X), Fract(position.Y));
            Vector2 blend = local * local * (new Vector2(3F) - (2F * local));
            float lowerLeft = Hash21(cell);
            float lowerRight = Hash21(cell + new Vector2(1F, 0F));
            float upperLeft = Hash21(cell + new Vector2(0F, 1F));
            float upperRight = Hash21(cell + Vector2.One);
            float lower = lowerLeft + ((lowerRight - lowerLeft) * blend.X);
            float upper = upperLeft + ((upperRight - upperLeft) * blend.X);
            return lower + ((upper - lower) * blend.Y);
        }

        /// <summary>
        /// Maps a two-dimensional lattice coordinate to a deterministic scalar value.
        /// </summary>
        /// <param name="value">The lattice coordinate.</param>
        /// <returns>A repeatable value in the range zero to one.</returns>
        private static float Hash21(Vector2 value)
        {
            // Wrap before the sine hash so large animated coordinates do not lose the
            // fractional precision that differentiates adjacent lattice cells.
            Vector2 wrapped = value - new Vector2(
                MathF.Floor(value.X / 256F) * 256F,
                MathF.Floor(value.Y / 256F) * 256F);

            return Fract(MathF.Sin(Vector2.Dot(wrapped, new Vector2(127.1F, 311.7F))) * 43758.5453F);
        }

        /// <summary>
        /// Evaluates one sparse, independently twinkling procedural star field.
        /// </summary>
        /// <param name="position">The effect-local pixel-center position.</param>
        /// <param name="scale">The size of each candidate star cell.</param>
        /// <param name="time">The animation time in seconds.</param>
        /// <param name="layer">The stable offset and density selector for this field.</param>
        /// <returns>The star brightness at the supplied position.</returns>
        private static float StarLayer(Vector2 position, float scale, float time, float layer)
        {
            // The hash decides whether a cell contains a star. The higher threshold on
            // the larger second layer keeps both apparent depths similarly sparse.
            Vector2 starPosition = position / scale;
            Vector2 cell = new(MathF.Floor(starPosition.X), MathF.Floor(starPosition.Y));
            float random = Hash21(cell + new Vector2(layer * 13F, layer * 7F));
            if (random <= 0.93F + (layer * 0.02F))
            {
                return 0F;
            }

            // A stable per-cell jitter avoids a visible grid. Only the intensity is
            // animated, so twinkling never changes a star's position or footprint.
            Vector2 jitter = new(
                Hash21(cell + new Vector2(1.7F + layer, 3.1F)),
                Hash21(cell + new Vector2(4.2F, 8.3F + layer)));

            jitter -= new Vector2(0.5F);
            Vector2 local = new(Fract(starPosition.X), Fract(starPosition.Y));
            float distance = (local - new Vector2(0.5F) - (jitter * 0.6F)).Length();
            float twinkle = 0.55F + (0.45F * MathF.Sin((time * (2F + (random * 7F))) + (random * 40F)));
            float point = 1F - SmoothStep(0F, 0.42F, distance);
            return point * twinkle * (0.7F + (0.6F * random));
        }

        /// <summary>
        /// Rotates a two-dimensional coordinate around the origin.
        /// </summary>
        /// <param name="position">The coordinate to rotate.</param>
        /// <param name="angle">The clockwise angle in radians.</param>
        /// <returns>The rotated coordinate.</returns>
        private static Vector2 Rotate(Vector2 position, float angle)
        {
            // Keep this explicit two-component rotation identical to the WGSL helper;
            // neither path depends on matrix packing or multiplication conventions.
            float cosine = MathF.Cos(angle);
            float sine = MathF.Sin(angle);
            return new Vector2(
                (cosine * position.X) - (sine * position.Y),
                (sine * position.X) + (cosine * position.Y));
        }

        /// <summary>
        /// Interpolates between two edges using a clamped cubic Hermite curve.
        /// </summary>
        /// <param name="edge0">The value mapped to zero.</param>
        /// <param name="edge1">The value mapped to one.</param>
        /// <param name="value">The value to interpolate.</param>
        /// <returns>The smoothed value in the range zero to one.</returns>
        private static float SmoothStep(float edge0, float edge1, float value)
        {
            // This is WGSL smoothstep's clamped cubic Hermite interpolation and keeps
            // every CPU color boundary aligned with the corresponding shader stage.
            float position = Math.Clamp((value - edge0) / (edge1 - edge0), 0F, 1F);
            return position * position * (3F - (2F * position));
        }

        /// <summary>
        /// Extracts the positive fractional component of a floating-point value.
        /// </summary>
        /// <param name="value">The value to split.</param>
        /// <returns>The fractional component in the range zero to one.</returns>
        private static float Fract(float value) => value - MathF.Floor(value);
    }
}
